{
 "title": "Pizza Dashboard",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Exceptions (DEV)",
   "type": "table",
   "gridPos": { "h": 11, "w": 21, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{component=\"jwt-pizza-service-dev\", type=\"exception\"} |= `` | json"
    }
   ]
  },
  {
   "title": "Factory Service Requests (DEV)",
   "type": "table",
   "gridPos": { "h": 11, "w": 15, "x": 0, "y": 11 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{component=\"jwt-pizza-service-dev\", type=\"factory\"} |= `` | json"
    }
   ]
  },
  {
   "title": "DB Logs (DEV)",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 22 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{component=\"jwt-pizza-service-dev\", type=\"db\"} |= `` | json"
    }
   ]
  },
  {
   "title": "HTTP Logs (DEV)",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{component=\"jwt-pizza-service-dev\", type=\"http\"} |= `` | json"
    }
   ]
  },
  {
   "title": "JWT Service Logs Example",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{component=\"jwt-pizza-service\"} |= `` | json"
    }
   ]
  },
  {
   "title": "Pizza creation latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "pizzaLatency_milliseconds_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "targets": [
    { "expr": "latency_milliseconds_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Revenue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    { "expr": "revenue_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pizzas Sold/minute, Creation Failtures/minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "targets": [
    { "expr": "rate(soldPizzas_total[1m])", "legendFormat": "__auto" },
    { "expr": "rate(pizzaFailures_total[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Auth attempts/minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "targets": [
    { "expr": "rate(authSuccess_total[1m])", "legendFormat": "__auto" },
    { "expr": "rate(authFailure_total[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Active users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
   "targets": [
    { "expr": "activeUsers_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "HTTP Requests/minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "rate(delRequests_total[1m])", "legendFormat": "__auto" },
    { "expr": "rate(requests_total[1m])", "legendFormat": "__auto" },
    { "expr": "rate(postRequests_total[1m])", "legendFormat": "__auto" },
    { "expr": "rate(putRequests_total[1m])", "legendFormat": "__auto" },
    { "expr": "rate(getRequests_total[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "memory_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cpu_percent", "legendFormat": "__auto" }
   ]
  }
 ]
}