{
 "title": "Pizza Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Pizza creation latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "pizzaLatency_milliseconds_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "latency_milliseconds_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Revenue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    { "expr": "revenue_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pizzas Sold/minute, Creation Failtures/minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "rate(soldPizzas_total[1m])", "legendFormat": "__auto" },
    { "expr": "rate(pizzaFailures_total[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Auth attempts/minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    { "expr": "rate(authSuccess_total[1m])", "legendFormat": "__auto" },
    { "expr": "rate(authFailure_total[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Active users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    { "expr": "activeUsers_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "HTTP Requests/minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "rate(delRequests_total[1m])", "legendFormat": "__auto" },
    { "expr": "rate(requests_total[1m])", "legendFormat": "__auto" },
    { "expr": "rate(postRequests_total[1m])", "legendFormat": "__auto" },
    { "expr": "rate(putRequests_total[1m])", "legendFormat": "__auto" },
    { "expr": "rate(getRequests_total[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "memory_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cpu_percent", "legendFormat": "__auto" }
   ]
  }
 ]
}